# -*- coding: utf-8 -*-
"""sms_spam_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k45vupZHm_SVYiq2jmSeo_M4qwpbm1fS
"""

import numpy as np
import pandas as pd

df = pd.read_csv(r"C:\Users\nraja\Downloads\archive (3)\spam.csv", encoding='latin-1')

df.head(1000)

df.shape

"""**1) Data Cleaning**"""

df.info()

"""Unnamed means most of the values are missing in the columns"""

# drop last 3 columns
df.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'],inplace=True)

df.sample(10)

# renaming the columns
df.rename(columns={'v1':'category','v2':'message'},inplace=True)
df.sample(10)

from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

df['category'] = encoder.fit_transform(df['category'])

df.head()

# missing values
df.isnull().sum()

# check for duplicate values
df.duplicated().sum()

# remove duplicates
df = df.drop_duplicates(keep='first')

df.duplicated().sum()

df.shape

"""**2) EDA**"""

df.head()

df['category'].value_counts()

import matplotlib.pyplot as plt
import seaborn as sns
import nltk

plt.pie(df['category'].value_counts(),labels=['ham','spam'],autopct="%0.2f")
plt.show()

import nltk

nltk.download('punkt')

nltk.download('punkt_tab')

# Length of the message
df['num_characters'] = df['message'].apply(len)

df.head()

df['num_words'] = df['message'].apply(lambda x: len(nltk.word_tokenize(x)))

df.head()

df['num_sentences'] = df['message'].apply(lambda x:len(nltk.sent_tokenize(x)))

df.head()

df[['num_characters','num_words','num_sentences']].describe()

# ham
df[df['category'] == 0][['num_characters','num_words','num_sentences']].describe()

# spam
df[df['category'] == 1][['num_characters','num_words','num_sentences']].describe()

sns.histplot(df[df['category'] == 0]['num_characters'])
sns.histplot(df[df['category'] == 1]['num_characters'],color='black')

sns.pairplot(df,hue='category')

sns.heatmap(df.drop(columns=['message']).corr(),annot=True)

"""**3. Data Preprocessing**


*   Lower case
*   Tokenization


*   Removing special characters
*   Removing stop words and punctuation


*   Stemming


"""

def transform_text(text):
  text = text.lower()
  text = nltk.word_tokenize(text)
  y = []
  for i in text:
    if i.isalnum():
      y.append(i)
  text = y[:]
  y.clear()
  for i in text:
    if i not in stopwords.words('english') and i not in string.punctuation:
      y.append(i)
  text = y[:]
  y.clear()

  for i in text:
    y.append(ps.stem(i))

  return " ".join(y)

nltk.download('stopwords')

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

# portstemmer
transform_text("Awesome, I remember the last time we got somebody high for the first time with diesel :V")

df['message'][300]

df['transform_text'] = df['message'].apply(transform_text)

df.head()

from wordcloud import WordCloud
wc = WordCloud(width=500,height=500,min_font_size=10,background_color='white')

spam_wc = wc.generate(df[df['category'] == 1]['transform_text'].str.cat(sep=" "))

plt.figure(figsize=(15,6))
plt.imshow(spam_wc)

ham_wc = wc.generate(df[df['category'] == 0]['transform_text'].str.cat(sep=" "))

plt.figure(figsize=(15,6))
plt.imshow(ham_wc)

df.head()

"""**Spam**"""

spam_corpus = []
for msg in df[df['category'] == 1]['transform_text'].tolist():
  for word in msg.split():
    spam_corpus.append(word)

len(spam_corpus)

from collections import Counter
Counter(spam_corpus).most_common(30)

sns.barplot(pd.DataFrame(Counter(spam_corpus).most_common(30))[0])

common_words_df = pd.DataFrame(Counter(spam_corpus).most_common(30))
sns.barplot(x=common_words_df[0], y=common_words_df[1])
plt.xticks(rotation='vertical')
plt.xlabel('Words')
plt.ylabel('Count')
plt.title('Most Common Spam Words')
plt.show()

"""**Ham (not spam)**"""

ham_corpus = []
for msg in df[df['category'] == 0]['transform_text'].tolist():
  for word in msg.split():
    ham_corpus.append(word)

len(ham_corpus)

from collections import Counter
Counter(ham_corpus).most_common(30)

sns.barplot(pd.DataFrame(Counter(ham_corpus).most_common(30))[0])

common_words_df = pd.DataFrame(Counter(ham_corpus).most_common(30))
sns.barplot(x=common_words_df[0], y=common_words_df[1])
plt.xticks(rotation='vertical')
plt.xlabel('Words')
plt.ylabel('Count')
plt.title('Most Common Ham Words')
plt.show()

df.head()

"""**4. Model Building**"""

from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
cv = CountVectorizer()
tfidf = TfidfVectorizer(max_features=3000)

X = cv.fit_transform(df['transform_text']).toarray()

X.shape

y = df['category'].values

y

X = tfidf.fit_transform(df['transform_text']).toarray()

X

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score

gnb = GaussianNB()
mnb = MultinomialNB()
bnb = BernoulliNB()

gnb.fit(X_train,y_train)
y_pred1 = gnb.predict(X_test)
print(accuracy_score(y_test,y_pred1))
print(confusion_matrix(y_test,y_pred1))
print(precision_score(y_test,y_pred1))

mnb.fit(X_train,y_train)
y_pred2 = mnb.predict(X_test)
print(accuracy_score(y_test,y_pred2))
print(confusion_matrix(y_test,y_pred2))
print(precision_score(y_test,y_pred2))

bnb.fit(X_train,y_train)
y_pred3 = bnb.predict(X_test)
print(accuracy_score(y_test,y_pred3))
print(confusion_matrix(y_test,y_pred3))
print(precision_score(y_test,y_pred3))

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier

svc = SVC(kernel='sigmoid', gamma=1.0)
knc = KNeighborsClassifier()
mnb = MultinomialNB()
dtc = DecisionTreeClassifier(max_depth=5)
lrc = LogisticRegression(solver='liblinear', penalty='l1')
rfc = RandomForestClassifier(n_estimators=50, random_state=2)
abc = AdaBoostClassifier(n_estimators=50, random_state=2)
gnb = GaussianNB()
xgb = XGBClassifier(n_estimators=50, random_state=2)
bc = BaggingClassifier(n_estimators=50, random_state=2)
etc = ExtraTreesClassifier(n_estimators=50, random_state=2)
gbdt = GradientBoostingClassifier(n_estimators=50, random_state=2)

clfs = {
    'SVC': svc,
    'KN': knc,
    'NB': mnb,
    'DT': dtc,
    'LR': lrc,
    'RF': rfc,
    'AdaBoost': abc,
    'Gb': gnb,
    'Xgb': xgb,
    'BgC': bc,
    'EtC': etc,
    'GBDT': gbdt
}

def train_classifier(clf,X_train,y_train,X_test,y_test):
  clf.fit(X_train,y_train)
  y_pred = clf.predict(X_test)
  accuracy = accuracy_score(y_test,y_pred)
  precision = precision_score(y_test,y_pred)
  return accuracy,precision

train_classifier(svc,X_train,y_train,X_test,y_test)

accuracy_scores = []
precision_scores = []

for name,clf in clfs.items():
  current_accuracy,current_precision = train_classifier(clf,X_train,y_train,X_test,y_test)
  print("For ",name)
  print("Accuracy - ",current_accuracy)
  print("Precision - ",current_precision)
  accuracy_scores.append(current_accuracy)
  precision_scores.append(current_precision)

performance_df = pd.DataFrame({'Algorithm':clfs.keys(),'Accuracy':accuracy_scores,'Precision':precision_scores}).sort_values('Precision',ascending=False)

performance_df

sns.barplot(x='Algorithm',y='Accuracy',data=performance_df)
plt.title('Accuracy Scores')
plt.xlabel('Algorithm')
plt.ylabel('Accuracy Score')
plt.xticks(rotation='vertical')
plt.show()

# model improve
# 1. Change the max_features parameter of TfIdf

temp_df = pd.DataFrame({'Algorithm':clfs.keys(),'Accuracy_max_ft_3000':accuracy_scores,'Precision_max_ft_3000':precision_scores}).sort_values('Precision_max_ft_3000',ascending=False)

temp_df = pd.DataFrame({'Algorithm':clfs.keys(),'Accuracy':accuracy_scores,'Precision':precision_scores}).sort_values('Precision',ascending=False)

new_df = performance_df.merge(temp_df,on='Algorithm')

new_df_scaled = new_df.merge(temp_df,on='Algorithm')

new_df_scaled

# Voting classifier
svc = SVC(kernel='sigmoid', gamma=1.0, probability=True)
knc = KNeighborsClassifier()
etcs = ExtraTreesClassifier(n_estimators=50, random_state=2)
from sklearn.ensemble import VotingClassifier
vc = VotingClassifier(estimators=[('svc', svc), ('knc', knc), ('etcs', etcs)], voting='soft')

vc.fit(X_train,y_train)

y_pred = vc.predict(X_test)
print("Accuracy",accuracy_score(y_test,y_pred))
print("Precision",precision_score(y_test,y_pred))

# Applying stacking
estimators = [('svc', svc), ('knc', knc), ('etcs', etcs)]
final_estimator = RandomForestClassifier()

from sklearn.ensemble import StackingClassifier

clf = StackingClassifier(estimators=estimators, final_estimator=final_estimator)

clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
print("Accuracy",accuracy_score(y_test,y_pred))
print("Precision",precision_score(y_test,y_pred))

import pickle
pickle.dump(tfidf,open('vectorizer.pkl','wb'))
pickle.dump(mnb,open('model.pkl','wb'))
